[tox]
envlist = qiskit, cirq
skipsdist = true

[testenv]
deps =
    -r requirements-dev.txt
commands =
    pytest {posargs:algorithms tests} -q

[testenv:qiskit]
deps =
    {[testenv]deps}
    -r requirements-qiskit.txt

[testenv:cirq]
deps =
    {[testenv]deps}
    -r requirements-cirq.txt
